### ISSUE TITLE
Optimize the drawString in the Renderer

### ISSUE THREAD

**Issue by michaelplatt07** [BambooSoftware/tloll#43]
// 1. Load a single instance of the alphabet.png at the init of the game.
    // 2. Default load the entire alphabet as individual sprites.
    // 3. Call out to each sprite based on the string being passed in (should be a map).
    // 4. Draw onto the screen.

**Comment by michaelplatt07** [comment]
Even with some optimizations thus far, without V-Sync being turned off, the FPS cap will only be as good as the monitor refresh rate.  In the case of my monitor, that is roughly 60 fps.  Without V-Sync, I'm sitting around 200-300 fps with no visible tearing.  Supposedly, tearing is only going to happen when the game is running at an FPS higher than the screen refresh rate.  Should we then keep the V-Sync off and cap the FPS at something we know will be playable?

**Comment by ablackbu** [comment]
Make v-sync user configurable and be done with it.
